name: base-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
- conda-forge

dependencies:
# Items required for basic level functionality
- gh-scoped-creds==4.1
- git==2.47.1
- jupyter-resource-usage=1.1.0
- jupyterhub==5.2.1
- jupyterlab==4.3.4
- jupyter_server==2.15.0
- jupyterlab-git==0.50.2
- jupytext==1.16.6
- nbgitpuller==1.2.1
- notebook==7.3.2
- python==3.11.*
- pip==24.3.1

- pandas==2.2.2

  # pip installed packages, conda is preferred
  - pip:
    - nbconvert[webpdf]==7.16.4
    - jupysql==0.10.15
