#!/usr/bin/env bash
set -euo pipefail

# installing chromium browser to enable webpdf conversion using nbconvert
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
playwright install chromium

# https://github.com/berkeley-dsep-infra/datahub/issues/5827
git config --system pull.rebase false

# overrides.json is a file that jupyterlab reads to determine some settings
# 1) remove the 'create shareable link' option from the filebrowser context menu
mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
cp -p overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings

# code-server's conda package assets are installed in share/code-server.
export VSCODE_EXTENSIONS=${CONDA_DIR}/envs/notebook/share/code-server/extensions
mkdir -p ${VSCODE_EXTENSIONS}

# This is not reproducible, and it can be difficult to version these.
for x in \
  ms-toolsai.jupyter \
  ms-python.python \
  quarto.quarto \
  ms-vscode.live-server \
  posit.shiny \
  reditorsupport.r \
  ; do
    code-server --extensions-dir ${VSCODE_EXTENSIONS} --install-extension $x
done

# Create a symbolic link for 'deno' in the specified directory structure
CONDA_PREFIX=/srv/conda/envs/notebook
if [[ -z "$CONDA_PREFIX" ]]; then 
    echo "CONDA_PREFIX is not set. Please activate your Conda environment."
    exit 1
fi

# Define the target directory for the symbolic link
TARGET_DIR="$CONDA_PREFIX/bin/tools/x86_64"

# Create the target directory if it does not exist
mkdir -p "$TARGET_DIR"

# Create the symbolic link for 'deno'
ln -s "$CONDA_PREFIX/bin/deno" "$TARGET_DIR/deno"

echo "Symbolic link created successfully at $TARGET_DIR/deno"

echo "CONDA_DIR=${CONDA_DIR}" >> .Renviron
