# run the action-lint-prs workflow on pull requests to this repo

name: "Lint workflow files on pull requests"
on:
  - pull_request  # yamllint disable-line rule:truthy

jobs:
  lint:
    uses: cal-icor/shared-workflows/.github/workflows/action-lint-prs.yaml@0.4.3